<?php
/**
 * FPVG_Frontend Class
 *
 * This class is responsible for all front-end functionality of the Flatsome Product Video Gallery plugin.
 * It handles script enqueueing and the logic for injecting the video placeholder into the product gallery
 * by leveraging both standard WooCommerce hooks and a Flatsome-specific theme filter.
 *
 * @package    Flatsome_Product_Video_Gallery
 * @subpackage Flatsome_Product_Video_Gallery/includes
 * @author     Neo
 */

// If this file is called directly, abort.
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class FPVG_Frontend {

	/**
	 * A unique placeholder string used to identify the video's position within the gallery array.
	 * This is not a real attachment ID and is used internally by the plugin.
	 *
	 * @since 1.1
	 * @var string
	 */
	const VIDEO_PLACEHOLDER = 'fpvg_video_placeholder';

	/**
	 * An HTML comment used as a temporary marker in the gallery's HTML output.
	 * This marker is safely injected and then replaced with the final placeholder <div>,
	 * preventing interference with Flatsome's gallery slider initialization.
	 *
	 * @since 1.1
	 * @var string
	 */
	const VIDEO_HTML_MARKER = '<!-- FPVG_VIDEO_REPLACEMENT_MARKER -->';

	/**
	 * Class constructor.
	 *
	 * Initializes the class and adds all necessary WordPress and Flatsome hooks to
	 * integrate the video functionality into the front-end product page.
	 *
	 * @since 1.0
	 */
	public function __construct() {
		// Enqueue frontend CSS and JavaScript assets.
		add_action( 'wp_enqueue_scripts', array( $this, 'enqueue_assets' ) );

		// Step 1: Inject our placeholder into the array of gallery image IDs.
		add_filter( 'woocommerce_product_get_gallery_image_ids', array( $this, 'add_video_placeholder_to_gallery_ids' ), 20, 2 );

		// Step 2: Intercept thumbnail generation to output our HTML marker for the placeholder.
		add_filter( 'woocommerce_single_product_image_thumbnail_html', array( $this, 'generate_html_marker' ), 10, 2 );

		// Step 3: Use Flatsome's final gallery HTML filter to replace our marker with the actual video placeholder div.
		add_filter( 'flatsome_single_product_images_html', array( $this, 'replace_marker_with_video_placeholder' ), 20, 2 );
	}

	/**
	 * Enqueues frontend scripts and styles.
	 *
	 * This method ensures that the plugin's CSS and JavaScript are loaded only on single
	 * product pages and only when a product video is actually present.
	 *
	 * @since 1.0
	 */
	public function enqueue_assets() {
		if ( ! is_product() ) {
			return;
		}

		global $product;
		if ( ! is_a( $product, 'WC_Product' ) ) {
			return;
		}

		$video_id = get_post_meta( $product->get_id(), '_fpvg_video_id', true );
		if ( empty( $video_id ) ) {
			return;
		}

		wp_enqueue_style(
			'fpvg-frontend-css',
			plugin_dir_url( __FILE__ ) . '../public/css/fpvg-frontend.css',
			array(),
			'1.1'
		);

		wp_enqueue_script(
			'fpvg-frontend-js',
			plugin_dir_url( __FILE__ ) . '../public/js/fpvg-frontend.js',
			array(), // No dependency on jQuery
			'1.1',
			true // Load in the footer.
		);
	}

	/**
	 * Adds a video placeholder to the product gallery image IDs array.
	 *
	 * @since 1.0
	 * @param array      $image_ids Array of gallery image attachment IDs.
	 * @param WC_Product $product   The current product object.
	 * @return array The modified array of image IDs including our placeholder.
	 */
	public function add_video_placeholder_to_gallery_ids( $image_ids, $product ) {
		if ( ! is_a( $product, 'WC_Product' ) ) {
			return $image_ids;
		}

		$video_id = get_post_meta( $product->get_id(), '_fpvg_video_id', true );

		if ( empty( $video_id ) ) {
			return $image_ids;
		}

		$position = get_post_meta( $product->get_id(), '_fpvg_video_position', true );
		$position = ! empty( $position ) ? absint( $position ) : 1;

		$position_index = max( 0, $position - 1 );

		array_splice( $image_ids, $position_index, 0, self::VIDEO_PLACEHOLDER );

		return $image_ids;
	}

	/**
	 * Generates a unique HTML marker for our video placeholder.
	 *
	 * @since 1.0
	 * @param string     $html          The default WooCommerce thumbnail HTML.
	 * @param int|string $attachment_id The attachment ID, or our placeholder string.
	 * @return string The original HTML, or our unique marker if it's the video placeholder.
	 */
	public function generate_html_marker( $html, $attachment_id ) {
		if ( self::VIDEO_PLACEHOLDER === $attachment_id ) {
			return self::VIDEO_HTML_MARKER;
		}
		return $html;
	}

	/**
	 * Replaces the HTML marker with the video placeholder <div>.
	 *
	 * This function hooks into a Flatsome-specific filter to find our unique HTML marker
	 * and replace it with a simple <div>. This div contains a unique ID and a data attribute
	 * with the video URL, which will be picked up by our frontend JavaScript.
	 *
	 * @since 1.1
	 * @param string $html       The complete gallery HTML generated by Flatsome.
	 * @param int    $product_id The current product ID.
	 * @return string The modified gallery HTML, now containing the placeholder.
	 */
	public function replace_marker_with_video_placeholder( $html, $product_id ) {
		if ( false === strpos( $html, self::VIDEO_HTML_MARKER ) ) {
			return $html;
		}

		$video_id = get_post_meta( $product_id, '_fpvg_video_id', true );
		$video_url = $video_id ? wp_get_attachment_url( $video_id ) : false;

		if ( ! $video_url ) {
			return str_replace( self::VIDEO_HTML_MARKER, '', $html );
		}
		
		// Construct the placeholder <div>. This is a simple, safe element that won't
		// interfere with theme scripts. Our JS will target this div to inject the video player.
		$placeholder_div = sprintf(
			'<div id="fpvg-video-placeholder" data-video-url="%s"></div>',
			esc_url( $video_url )
		);

		// Replace our marker with the placeholder div.
		return str_replace( self::VIDEO_HTML_MARKER, $placeholder_div, $html );
	}
}
